version: "3.8"
services:
  backend:
    container_name: noteams-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
