version: "3.8"
services:
  backend:
    container_name: backend_server
    image: fixfireza/noteams-backend:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/g64070148/.config/gcloud:/root/.config/gcloud
